### ISSUE TITLE
GenModule instance has no attribute 'print_error'

### ISSUE THREAD

**Issue by xinxin999** [Mr-Un1k0d3r/DKMC#35]
[](url)`(generate)>>> run
Traceback (most recent call last):
  File "dkmc.py", line 43, in <module>
    mod.show_menu()
  File "C:\Users\lijx\Desktop\DKMC-master\module\module.py", line 21, in show_menu
    self.do_action()
  File "C:\Users\lijx\Desktop\DKMC-master\module\module.py", line 42, in do_action
    self.exec_action(data)
  File "C:\Users\lijx\Desktop\DKMC-master\module\module.py", line 57, in exec_action
    self.run_action()
  File "C:\Users\lijx\Desktop\DKMC-master\module\gen.py", line 30, in run_action
    data = self.get_file_data()
  File "C:\Users\lijx\Desktop\DKMC-master\module\gen.py", line 66, in get_file_data
    self.print_error("%s not found" % self.vars["source"][0])
AttributeError: GenModule instance has no attribute 'print_error'`

no matter windows or Linux
both questions
how to solove?
thanks

**Comment by Mr-Un1k0d3r** [comment]
good catch I fixed the issue with the following commit: https://github.com/Mr-Un1k0d3r/DKMC/commit/3c238f01a8a62f4e035a76769b003b11cdb75d17

the `self.print_error` was supposed to be `self.ui.print_error`.

You should now see the error in the UI. In your case the source file was not found.
